


def DNA(s):
        
        s=str(s)
        aCount=0
        cCount=0
        gCount=0
        tCount=0

        

        for item in s:
                item=item.upper()

                if item == 'A':
                        aCount+=1
                if item == 'C':
                        cCount+=1
                if item == 'G':
                        gCount+=1
                if item == 'T':
                        tCount+=1
        print(aCount,cCount,gCount, tCount)
        return(aCount,cCount,gCount, tCount)

s='GGAGTGTAGGATCCTATACGTCCCCAACCAGCGTGAGAACGTACGTTCTATATCCCCTAATACTCATTGGCAAGCGTGTAGACGGTCAACCCCAGCACGGGCCTCAACCTCGGGTGGCGACCTCCGGAGAACCGGTTAGGTGCCCTAGAGCTTGATAGTACACCCTTCGGGGGCGTCTGCTTAAGAATGTAAATGTTATATATGATGAACGCAGACGGTCTTCCATAGCGTGCCCATTATGCTATGTATAAGTCGCAACGGGCGCTCGGCTGCTCGAACTATTTGCTGGCGGACTCAAATACAAGAGCTTATAGTGCCGACGGCGTTTCACTGCCTTACAGCTGCATGGGTATATACGTCCCGATGAGGCACATGATCTGGGGAGTGCTGGTCCATGCATACAGATCACATTAGTTACAGGTTGTCATGCATGGTAATCGCCATTGCTTCTTTTCCACCAATTACGACCATGTGGTTTCGGGGTATATGCGTTGCCACCGGGGCCTTAAAAGTGCAATAGTTATCTAGGGCCCGCAGGAACTAATCTAGCAATTTATCTTAACCACATTCCTATATTCACTCCCCGTCAGGGATCTCTAGATAACTTTCCAGTCCGCATACTTGACGAAATCAACGTCTGAAAACAACGACAGAGTAGGACTGTGCGTTGAAACATACTCCCTCTAAACACACAACAGGCAGGCTAGGAAGCATTAACGTATGTTCCGCACAGTCATGAACACATACGGAGGCAGAATTTATTCCCCAGAGTACACTCCCAAGCTTTCTTATAACTGGCTACGAACGTATAGACAATAGAGAGCCGTGTGAAATTCGTCCGGAAGACGACCACTT'                
DNA(s)
