


def REVC(s):
        s=s[::-1]
        #print(s)
        reverse=''
        for item in s:
                item=item.upper()

                if item == 'A':
                        reverse+='T'
                if item == 'C':
                        reverse+='G'
                if item == 'G':
                        reverse+='C'
                if item == 'T':
                        reverse+='A'
        print(reverse)
       # return(aCount,cCount,gCount, tCount)

s='CTGCCCCATGGTTTATTTTCGGACTGCTAAAGATAGAGGGAAGGCCTAGTAGACGTTTAGGTTGCAACCGCCGTATTAGAAGGCTGGTCACAGTTGATGTTGTGTTACCGATAGCGCGGCATTAGGACCCGTCCAGGACTTCAGGCGAATTTAAGCTAGATCTCCATACGCATGCTACACTTTGGCAGGATAACGTGGCATCAGCAGGACATGGGGCCGCCCGATACGTTGCTCTCGGTTTTAATTTTGTCACCTCCGGGTAGGATTGTTGGCAGCCTAAGAATGTGGGAGCTGTTTACCTCGCGATTTTCCCCAGTCGCTTTCTCTCTTGTCATTCGTTTAGCCTAGACGACGATCACATAAATGCGACCCGAACACGCCCGTTAGCCTTTCATATTTGCTATACTAGGCTATTATCAGGTAAGACCTTCGGGAAAATGTATGGTGACACAAAGAGCCGCGTACTACGGAGCTCGTTCCGAGAGCGCAGGAGCGTTCATAGCCGATTTGGATCCAACACCCCAACTGGAAGAAGAATTACATACTCAGACTCGTGACCGGTGGGCGCGACGTCAGTTGTTTCACGACAGACAATGTCAAAGTAACTAATGCTGGCCCCAGGGTTGAATGACAGTTACACTGAAATGCTTTTCGTTTTCCTTTTCGATTTGGCTATACGCCCGCAGCTTTCGAGTTGCTCCGACATCCGGTTTTTCGATAAATCCTATATCTTACCAGGGCTAATCTTTGCCCGGATTTATGTTAACTGCCCAAACCCTTCAAAATCGGGTTTCCTGAGCCCTGTTCCTGAGGAGGAAATGATCTTCGGCACCGACAACCAACGTCGCGAGGCATTATATTGCCTCACTCTACTCCTCCGATCTGGGTGCAATTCAAATGTAACTCGGATTTGTGGCAAACGCTAAGTAATCCTTGGACATCTCGCAACCCGGTCGGGAGGATCTGAACCTTGG'                
REVC(s)
