
def SUBS(s,t):
        '''input : 2 DNA strings, s and t
        t is a subset of s, will find positions
        where t occurs in s
        outputs indices of positions'''
        posList=list()
        bigLen=len(s)
        smallLen=len(t)

        for nucStretch in range(0,bigLen+1):
               
                if t in s[nucStretch:smallLen+nucStretch]:
                        
                        posList.append(nucStretch+1)
        print(*posList)

s='AGTCTGGCCATTCTGGCCTCTGGCCGCCCACTCTGGCCAGTCTGGCCGGTGCGCGTTCTGGCCTGCATCTGGCCCTCAAACGTGCCAGTCTGGCCTGTCTGGCCTTTCTGGCCTCTGGCCCATCTGGCCGCGTCTGGCCACATCTGGCCTATCTGGCCACAGATCTGGCCAGACTGACTCGACGCAACGGATCTGGCCGTCTGGCCAATCCGTTCTGGCCTCTGGCCTCTGGCCTTTCTGGCCATTTCTGGCCGGTCTGGCCTCTCTGGCCGTGCGATCTGGCCGTCTGGCCTCTGGCCGGTCTGGCCGTCTGGCCTCTGGCCATCATCGAGGATCTGGCCTCTGGCCTTGAATCTGGCCTCTGGCCGTAACATCTGGCCTCTGGCCCTAGTACGTCTGGCCCTCTGGCCGGGTCTGGCCGCATCTGGCCTCTGGCCAGTCTGGCCTCTGTCTGGCCTCTGGCCGTCTGGCCTCTGGCCGTTCTGGCCGTTCTGGCCCCTCTGGCCATCTTATCTGGCCGGGTCTGGCCTATCTGGCCGGCTCAGTCTGGCCAGATCTGGCCTCTGGCCTCTGGCCGATCTGGCCAGTCTGGCCTCTCTGGCCTCTGGCCTCTGGCCTCTGGCCATAGCGATCTGGCCTCTGGCCTCTGGCCATCTGGCCTCTGGCCTCTGGCCTCACTCTGGCCATCTGGCCAGTCTGGCCGCTCTGGCCAAGGATCTGGCCTTCTGGCCCTCTGGCCCTTCTGGCCATCTGGCCAATGGTCTGGCCCTACCCGTCTGGCCGAGATCTGGCCGTCTGGCCGGCATCTCTGGCCTCCTAGTCTGGCCTCTGGCCATCATTGATCTGGCCTCTGGCCTTCTGGCCTCTGGCCTCTGGCCTTTTTTCTGGCCCTTAATCTGGCCAACTGTCTGGCCTCTGGCCGTCTGGCCTCTGGCC'
t='TCTGGCCTC'
SUBS(s,t)
                        
                        

